### ISSUE TITLE
Diskbrowser.jar stopped launching

### ISSUE THREAD

**Issue by hoserama99** [dmolony/DiskBrowser#7]
Setup: macOS 10.13.6, JRE 10.0.2 installed.

I installed the JRE last night and was able to launch DiskBrower.jar fine. Shut down my Mac for the night. Restarted today and now the app no longer launches.

Here's what I think is the relevant Terminal output, if that helps:

```
ThunderTouch:~ boliver$ /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar /Users/boliver/Downloads/DiskBrowser.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.desktop/java.awt.Window.init(Unknown Source)
	at java.desktop/java.awt.Window.<init>(Unknown Source)
	at java.desktop/java.awt.Frame.<init>(Unknown Source)
	at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
	at com.bytezone.diskbrowser.gui.DiskBrowser.<init>(DiskBrowser.java:27)
	at com.bytezone.diskbrowser.gui.DiskBrowser$2.run(DiskBrowser.java:211)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
ThunderTouch:~ boliver$ /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

```

**Comment by hoserama99** [comment]
Java is not my strong suit, so I'm unsure how to further diagnose this. I will say that "/usr/bin/java -version" reports Java 8, but I think that's to be expected?

**Comment by dmolony** [comment]
Hi Brad

This is a mystery. Do you still have java 8 installed on your machine? And did you perhaps invoke java 8 the next day instead of java 10? Did you start DiskBrowser the same way (from the same location) both days?

I have the following aliases set up on my machine:

alias setjdk10='export JAVA_HOME=$(/usr/libexec/java_home -v 10)'
alias setjdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'

When I try to run DiskBrowser under java10 it works fine, but if I change to java 8 it fails:

MBP3:~/Dropbox/Java $ java -jar DiskBrowser.jar

MBP3:~/Dropbox/Java $ setjdk8

MBP3:~/Dropbox/Java $ java -jar DiskBrowser.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/bytezone/diskbrowser/gui/DiskBrowser has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)


I see it's a different error, but it may be related to the issue of using different runtimes.

Let me know if this helps or not.

Cheers

Denis

**Comment by hoserama99** [comment]
I do have the Java 8 runtime installed, yes. Possibly even the JDK for 8, although I'm less clear on that.

I only installed the JRE for Java 10, not the JDK. Maybe this is part of the problem?

Following on from that:

```
ThunderTouch:~ boliver$ setjdk10                                                                                                                                                                    
Unable to find any JVMs matching version "10".
ThunderTouch:~ boliver$ setjdk8
ThunderTouch:~ boliver$ 
```

As for running the app, I launched it via the Finder initially, by double-clicking on the jar. That failed until I installed the JRE v10 runtime, then it worked. Today, however, it always fails - it just silently quits. That's when I got the bright idea to try to launch it manually in the terminal, which is what you see in my first post.

I then tried to launch it with /usr/bin/java and got the same runtime error as you posted about the runtime mismatch. /usr/bin/java -version tells me it's 1.8, so the failure is not surprising.

Again, I'm pretty unfamiliar with Java so it's unclear to me if I need to also install the Java 10 JDK or uninstall Java 8 or what. I'll take a stab at installing the v10 JDK and see where that gets me. Maybe I'll figure out what older app caused me to install Java 8 in the process. ;-)

Thanks again for the help.

**Comment by dmolony** [comment]
Theoretically JRE 10 should be fine, but I have the JDK installed so I can't prove that.

You should be able to live with both 8/10 if you use the setJDKxx commands I showed you.

Good luck.

**Comment by hoserama99** [comment]
OK, installed the v10 JDK. The bad news: no change. Here's how it shakes out:

```
ThunderTouch:~ boliver$ which java
/usr/bin/java
ThunderTouch:~ boliver$ setjdk10
ThunderTouch:~ boliver$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
ThunderTouch:~ boliver$ java -jar /Users/boliver/Downloads/DiskBrowser.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.desktop/java.awt.Window.init(Window.java:509)
	at java.desktop/java.awt.Window.<init>(Window.java:549)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at com.bytezone.diskbrowser.gui.DiskBrowser.<init>(DiskBrowser.java:27)
	at com.bytezone.diskbrowser.gui.DiskBrowser$2.run(DiskBrowser.java:211)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

I'll keep poking at this as time permits. That it would stop working after a shutdown/restart is weird, so maybe if I restart again, it'll start working? ;)

**Comment by hoserama99** [comment]
> That it would stop working after a shutdown/restart is weird, so maybe if I restart again, it'll start working?

Unbelievably, I restarted macOS and it now launches again. When I retire, there will be no computers allowed in the cave.

Thanks again for the help. I'll close this although I can't say the solution is particularly satisfying. Feel free to reopen if you want to continue to track this.

**Comment by dmolony** [comment]
This is getting even weirder. Do you have to restart twice each time now ???

**Comment by hoserama99** [comment]
I will let you know tomorrow but I sure hope not. It would be amusing though.

There is one possibility at play: yesterday, I set DiskBrower's "HOME" directory, and it's a network-mounted share. When I launched DiskBrowser after restart #2 today, I forgot to mount the drive first (oops!) and it fired right up and asked me to choose a HOME directory, as if it'd never been set. It could be entirely unrelated, but if it happens again, I'll pay closer attention to the state of the mounted share.

**Comment by hoserama99** [comment]
Ok, ran tests today.

First launch from cold power-off: not working
Restart: working
Restart after unrelated kernel panic: not working
Restart again: working
Restart again: working

Maybe the v10 JRE is buggy in certain scenarios, maybe there's some quirk to my setup, maybe all of the above. If you can suggest a more exhaustive way to diagnose, I'm game but I'm also content to chalk this up to "Java+macOS+my setup" being unorthodox in some hard-to-determine way.

**Comment by dmolony** [comment]
Have you tried it on a different machine?

I always use the JDK, so I can't help with the JRE theory, but certainly something on your Mac seems to be wrong. All I can suggest is to purge your machine of all old versions of Java and DiskBrowser, and reinstall just one fresh copy of each.
