### ISSUE TITLE
Doesn't launch on macOS 10.14.4 with latest Java SDK

### ISSUE THREAD

**Issue by Tiza59** [dmolony/DiskBrowser#9]
Config: macOS 10.14.4, Java SE Development Kit 12

Error message:
Apr  8 08:45:06 iMac com.apple.preference.security.remoteservice[5098]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Apr  8 08:45:56 iMac Jar Launcher[5104]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug.

Thanks for any advice
Tiza59

**Comment by dmolony** [comment]
Hi

I have no idea what the problem is. My machine is also a Mac running 10.14.4 with SDK 12. I cannot reproduce the problem.

Is there a stack trace?

**Comment by Tiza59** [comment]
Thank you for your fast answer and great piece of software. I could launch diskbrowser.jar easily from the command line. Seems that double-clicking jars needs some effort on newer macOS to prevent the "could nor be opened, check Console for more info"-message.

P.S. Terminal messages after successful launch:
java -jar /Applications/Utilities/DiskBrowser.jar 
No root directory
Font name not stored 
Font size not stored 
No file tab
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.bytezone.diskbrowser.gui.DiskLayoutImage$MyMouseListener.mouseClicked(DiskLayoutImage.java:257)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Unknown 000002BC

**Comment by dmolony** [comment]
Hi

Do you have the latest version? I just tried double-clicking the latest jar, and also running it from the command line. Both worked fine, with no errors or other messages.

I really can't think what would be causing your issues.

Regards

Denis

**Comment by Tiza59** [comment]
I have downloaded latest diskbrowser.jar from your release page which is just 1 commit older than trunk. I have no idea either want went wrong, I´ll let you know if find my problem. Cheers

**Comment by dmolony** [comment]
I have just created a new release which will allow you to reset your preferences if required. Just add '-reset' to the end of the command line.

I just tried it on my system, and it prints the following:

MBP3:~/Dropbox/Java $ java -jar DiskBrowser.jar -reset
No root directory
No file tab

After setting the root folder and quitting, the next run displayed no output.

Hope this helps.

Denis

**Comment by Tiza59** [comment]
Hello Denis,

Thank you for your great Disk Browser!

I’m an Apple /// Enthusiast and have just digitized 500+ Disk around 1983 in WOZ format.

Either plenty of that disk are empty or you are not supporting the SOS 1.1 - SOS 1.3 disks.
Please find 2 Disk include for examination. If you wan’t support for that format, please let me know,
I have access to most of the reference  literature from that time.




Kind regards from Germany, stop by and I would glad to buy food and beer for you!
Uwe

**Comment by dmolony** [comment]
Hi

I don't know if DiskBrowser supports SOS because I don't have anything to test with. And there seems to be no disks attached. If you send me the disks and documentation I would be happy to look at it.

Cheers

Denis

**Comment by Tiza59** [comment]
Hi Denis,

Thank you for your fast answer. Please start with
http://www.apple3.org/Documents/Manuals/Apple%20III%20SOS%20Reference%20Manual%20Volume%201%20-%20How%20SOS%20Works.PDF <http://www.apple3.org/Documents/Manuals/Apple%20III%20SOS%20Reference%20Manual%20Volume%201%20-%20How%20SOS%20Works.PDF>
In chapter 5 of this reference manual you find documentation how SOS stores blocks on block devices.
Prodos and SOS 1.3 are pretty much alike.

If you want me to send some sample disks, please write a real Email to uwefalck@mac.com <mailto:uwefalck@mac.com>.
Ive tried to include some disks within this thread but apparently they have been filtered out by Github.

Cheers from Germany
Uwe

> Am 23.10.2019 um 00:05 schrieb Denis Molony <notifications@github.com>:
> 
> Hi
> 
> I don't know if DiskBrowser supports SOS because I don't have anything to test with. And there seems to be no disks attached. If you send me the disks and documentation I would be happy to look at it.
> 
> Cheers
> 
> Denis
>
